export const hebrewDictionary = {
  friends: "חברים",
  personalDetails: "פרטים אישיים",
  business: "עסק",
  businesses: "עסקים",
  businessName: "שם העסק",
  businessDescription: "תיאור העסק",
  businessAddress: "כתובת העסק",
  businessPhoneNumber: "מספר טלפון של העסק",
  businessEmail: "אימייל של העסק",
  businessWebsite: "אתר אינטרנט של העסק",
  businessSocialMedia: "רשתות חברתיות של העסק",
  hey: "היי",
  welcome: "ברוכים הבאים",
  welcomeToViby: "ברוכים הבאים ל viby",
  myBusinesses: "העסקים שלי",
  allBusinesses: "כל העסקים",
  follow: "עקוב",
  following: "עוקב",
  unfollow: "בטל מעקב",
  lastVisit: "ביקור אחרון",
  myLastVisit: "הביקור האחרון שלי",
  links: "לינקים",
  inviteFriends: "הזמנת חברים",
  allMyAppointments: "כל התורים שלי",
  paymentAddress: "אמצעי תשלום",
  appointmentsHistory: "היסטורית תורים",
  chatInvite: "בואו נשוחח",
  booked: "נקבע",
  cancelled: "בוטל",
  completed: "הושלם",
  close: "סגור",
  client: "לקוח",
  worker: "עובד",
  appointmentDetails: "פרטי תור",
  meetingsForToday: "פגישות להיום",
  selectDate: "בחר תאריך",
  appointmentsManagement: "ניהול תורים",
  noAppointments: "אין פגישות ליום זה.",
  loadingAppointments: "טוען פגישות...",
  errorLoadingAppointments: "שגיאה בטעינת הפגישות: ",
  status: "סטטוס: ",
  time: "שעה: ",
  service: "שירות: ",
  date: "תאריך: ",
  clientDetails: "פרטי לקוח: ",
  loading: "טוען...",
  chooseDate: "בחר תאריך",
  currentAppointments: "תורים נוכחיים",
  cancel: "ביטול",
  confirm: "אישור",
  confirmDelete: "האם אתה בטוח שברצונך למחוק את התור הזה?",
  noAvailableAppointments: "אין תורים זמינים לתאריך זה.",
  selectWorkerToSeeTimes: "בחר עובד כדי לראות את הזמנים הזמינים",
  selectDay: "בחר יום",
  selectService: "בחר שירות",
  selectWorker: "בחר עובד",
  bookAppointment: "קביעת תור",
  successfullAppointment: "התור נקבע בהצלחה!",
  logOut: "התנתקות",
  confirmImageUplaod: "האם אתה בטוח שתרצה להחליף את תמונת הפרופיל שלך?",
  editImage: "עריכת תמונה",
  name: "שם",
  email: "אימייל",
  phone: "טלפון",
  InvalidPhoneNumber: "מספר הטלפון לא תקין",
  InvalidMail: "כתובת המייל לא תקינה",
  MailRequired: "אימייל הוא שדה חובה",
  NameRequired: "שם הוא שדה חובה",
  updateSuccess: "הפרטים שלך עודכנו בהצלחה",
  businessCreated: "העסק נוצר בהצלחה!",
  profileUpdated: "הפרופיל עודכן בהצלחה!",
  completeProfile: "השלם את הפרופיל שלך",
  isBusinessOwner: "האם אתה בעל עסק?",
  gender: "מין",
  male: "זכר",
  female: "נקבה",
  other: "אחר", 
  workingHours: "שעות פעילות",
  chooseGender: "בחר מגדר",
  noBusinessesToDisplay: "אין לנו עסקים להציג לך",
  notFollowingBusinesses: "אתה לא עוקב אחרי עסקים",
  businessesYouDontKnow: "עסקים שעוד לא הכרת"
};
