export const hebrewDictionary = {
    friends: 'חברים',
    personalDetails: 'פרטים אישיים',
    business: 'עסק',
    businesses: 'עסקים',
    businessName: 'שם העסק',
    businessDescription: 'תיאור העסק',
    businessAddress: 'כתובת העסק',
    businessPhoneNumber: 'מספר טלפון של העסק',
    businessEmail: 'אימייל של העסק',
    businessWebsite: 'אתר אינטרנט של העסק',
    businessSocialMedia: 'רשתות חברתיות של העסק',
    hey: 'היי',
    welcome: 'ברוכים הבאים',
    myBusinesses: 'העסקים שלי',
    allBusinesses: 'כל העסקים',
    follow: 'עקוב',
    unfollow: 'בטל מעקב',
    lastVisit: 'ביקור אחרון',
    myLastVisit: 'הביקור האחרון שלי',
    links: 'לינקים',
    inviteFriends: 'הזמנת חברים',
    allMyAppointments: 'כל התורים שלי',
    paymentAddress: 'אמצעי תשלום',
    appointmentsHistory: 'היסטורית תורים',
    chatInvite: 'בואו נשוחח'
}